<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>code-runner.output</string>
        <key>name</key>
        <string>code-runner-output</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\[Running\])(.*)</string>
                <key>name</key>
                <string>code-runner.running</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>token.debug-token</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>token.error-token</string>
                    </dict>
                    <key>5</key>
                    <dict>
                        <key>name</key>
                        <string>string</string>
                    </dict>
                    <key>6</key>
                    <dict>
                        <key>name</key>
                        <string>constant.numeric</string>
                    </dict>
                    <key>7</key>
                    <dict>
                        <key>name</key>
                        <string>string</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\[Done\])(.+)(?:(code=0)|(code=\d+))([^\d]+)(\d+(?:\.\d+)?)([^\d]+)</string>
                <key>name</key>
                <string>code-runner.done</string>
            </dict>
        </array>
    </dict>
</plist>